name: "tests"

on:
  pull_request_target: # Use pull_request_target
    branches: [main]

jobs:
  run-specs:
    name: run specs
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        run: ./vagrant-deploy.sh
      - name: tests
        run: ./vagrant-tests.sh
